### ISSUE TITLE
How to support password?

### ISSUE THREAD

**Issue by summerinsects** [Mwni/pixi-text-input#10]
How to replace input with *'s(or any other password character, eg black dot •)

**Comment by Mwni** [comment]
Not supported at the moment.
You could turn the native text input to a password input and disable the pixi-substitution.

```
input.htmlInput.setAttribute('type', 'password')
input.substituteText = false
```

Drawback is, that the input will always be on top of your pixi-content. Is that an option?

**Comment by summerinsects** [comment]
THX
