### ISSUE TITLE
Ability to set custom attributes

### ISSUE THREAD

**Issue by sheerun** [Mwni/pixi-text-input#16]
I'd like to set following attributes so all spellcheck etc. features are disabled for input:

```
        autocorrect: 'off',
        autocomplete: 'off',
        autocapitalize: 'off',
        spellcheck: false

```

Unfortunately these cannot be set as styles but attributes of input. Is it possible? Could you please add this feature?

**Comment by Mwni** [comment]
The native html text input is exposed via `yourInput.htmlInput`
you can apply all special properties via
`yourInput.htmlInput.setAttribute('autocorrect', 'off')`

**Comment by sheerun** [comment]
ok thank you!
