### ISSUE TITLE
Text align center not supported

### ISSUE THREAD

**Issue by jounia** [Mwni/pixi-text-input#18]
Text alignment doesn't work in the Pixi.Text surrogate, probably because HTML Input style is "textAlign" and for Pixi.Text just "align". I can set textAlign in the input options and it works, but if I have substituteText set true, the surrogate just goes to the left when the text input is unfocused.

It would probably be easy to fix by adding an exception for it to the `_deriveSurrogateStyle`?

**Comment by Mwni** [comment]
> It would probably be easy to fix by adding an exception for it to the _deriveSurrogateStyle?

yes that should be a trivial fix. let me know if it works, otherwise i'll take a look.

**Comment by jounia** [comment]
I tried adding it there... The TextStyle gets the correct `align` property but for some reason the surrogate still stays to the left. Can you take a look?

**Comment by jounia** [comment]
Okay, I figured it out when trying to get sleep last night... 😄 Pixi.Text is of course only the width of the text it contains, so it has to be positioned manually, so in `_deriveSurrogateStyle` I put:

`switch (this._surrogate.style.align) {`
`            case 'left':`
`                this._surrogate.x = padding[3];`
`                break;`
`            case 'center':`
`                this._surrogate.x = input_bounds.width * 0.5 - this._surrogate.width * 0.5;`
`                break;`
`            case 'right':`
`                this._surrogate.x = input_bounds.width - padding[1] - this._surrogate.width;`
`                break;`
`        }`

And it works.

**Comment by Mwni** [comment]
Nice one! Can I merge this code?

**Comment by jounia** [comment]
Sure, but keep in mind it doesn't work without the "align" exception in `_deriveSurrogateStyle`:

`case 'textAlign':`
`                    style.align = this._input_style.textAlign;`
`                    break`

And I of course meant that I put the code in my previous post in `_updateSurrogate` function, apologies.

**Comment by Mwni** [comment]
https://github.com/Mwni/PIXI.TextInput/commit/a7e48f4697d61104d1d2fc8da9d43ab94ddd1c35
