### ISSUE TITLE
Bug : when deleting, onkeydown not fire

### ISSUE THREAD

**Issue by Makio64** [Mwni/pixi-text-input#23]
When you press back arrow ( to delete the previous character ) the onkeydown is not called.

**Comment by Makio64** [comment]
the property `input.text` is not update and different from `input.htmlInput.value`

**Comment by Mwni** [comment]
If you look at the source code, both things are forwarded directly, input.text is infact input.htmlInput.value, and they keydown event is piped through unconditionally. must be your browser or OS.

**Comment by Makio64** [comment]
I tested and report all bug on windows chrome.

it probably come from something like that : 
https://stackoverflow.com/questions/2353550/how-to-capture-a-backspace-on-the-onkeydown-event/2353562

For peoples looking to a quickfix:
```
this.latestValue = ''
const onUpdate=() => {
	if (this.input.htmlInput.value != this.latest) {
		this.onType()
	}
	requestAnimationFrame ( onUpdate )
}
requestAnimationFrame ( onUpdate )
```
