### ISSUE TITLE
Request : method dispose to clean memory

### ISSUE THREAD

**Issue by Makio64** [Mwni/pixi-text-input#24]
It would be great to add a dispose methods to cleanup the dom, listeners etc.. from memory

**Comment by Mwni** [comment]
`removeChild(input)` + `input.destroy()` does what you want

**Comment by Makio64** [comment]
Thanks, I would suggest to add the .destroy() in the doc :)

**Comment by Mwni** [comment]
Agree, though the destroy method exists on every pixi displayobject, so it is to be known nevertheless.
