### ISSUE TITLE
Bug : inconsistent behavior when using paddingTop

### ISSUE THREAD

**Issue by Makio64** [Mwni/pixi-text-input#25]
when using some combinaison the focus position of the text is different than the blur position

for example with
```
			input: {
				lineHeight: '40px',
				fontSize: '14px',
				padding: '16px',
				paddingTop: '18px',
				paddingLeft: '14px',
				paddingBottom: '8px',
				width: '200px',
				color: '#5b1289',
			},

```

**Comment by Mwni** [comment]
Sadly there's no way to tell the exact font height and baseline position, which is why the blur position is different for some fonts on some configs. If that's a problem, set `substituteText` to false.
