### ISSUE TITLE
Set input type

### ISSUE THREAD

**Issue by Freeroed** [Mwni/pixi-text-input#28]
Hi!
I try to use Your module for login form in my game, I noticed that there is no way to set different input types, for example "password".
Having looked at the code, I decided that adding it would not be difficult.
For example update method:
_createDOMInput(type){
    if(this._multiline){
      this._dom_input = document.createElement('textarea')
      this._dom_input.style.resize = 'none'
    }else{
      this._dom_input = document.createElement('input')

      this._dom_input.type = type
    }

and set type as constructor parameter 
styles, type

**Comment by Mwni** [comment]
This plugin is only designed for text input, with the exception of textareas for multiline. Checkboxes, radios, ranges and files wont play well with it. Having the ability to use it as a password input is valid however. So my proposal would be to introduce a boolean like `displayAsPassword` that switches the type internally and also makes sure the pixi surrogate wont display the password as plaintext.

Until I find time to implement this you can do this:
```
input.htmlInput.type = 'password'
input.substituteText = false
```

**Comment by Freeroed** [comment]
Ok! Thanks)
