### ISSUE TITLE
Does not handle type 'password'

### ISSUE THREAD

**Issue by radrevere** [Mwni/pixi-text-input#31]
_deriveSurrogateText on line 423 needs to be updated to handle password type.  The following is the code I used to handle it for my project:
_proto._deriveSurrogateText = function _deriveSurrogateText() {
      var txt = this._dom_input.value;
      if(this._dom_input.value.length === 0)
      {
        txt = this._placeholder;
      }else if(this._dom_input.type == 'password'){
        txt = "•".repeat(this._dom_input.value.length);
      }
      return txt;
    };

**Comment by Mwni** [comment]
Thank you for this. Do you have a fork form which you can make a pull request or should I do it myself and credit you in the commit?

**Comment by radrevere** [comment]
You are welcome.  I didn't fork it so you can feel free to make any changes so that it matches your coding standards.

**Comment by Mwni** [comment]
Checked and merged. Have a good weekend.
