### ISSUE TITLE
PIXI v7 Support

### ISSUE THREAD

**Issue by tolmasoft** [Mwni/pixi-text-input#41]
Hi. I download and modify this code for my project =)

Modify functions:

**_createSurrogate()**

```
this._surrogate_hitbox.eventMode = 'static';
if (PIXI.VERSION[0] != '7') this._surrogate_hitbox.interactive = true;
```

**_updateSurrogateHitbox(bounds)**

```
this._surrogate_hitbox.eventMode = this._disabled?'auto':'static';
 if (PIXI.VERSION[0] != '7') this._surrogate_hitbox.interactive = !this._disabled;
```

    

**_createSurrogate()**

       
```
this._surrogate_hitbox.eventMode = 'static';
if (PIXI.VERSION[0] != '7') this._surrogate_hitbox.interactive = true;

/*some code....*/        

this.addChild(this._surrogate_mask, this._surrogate, this._surrogate_hitbox);
```

**Comment by Mwni** [comment]
Hey Vladislav, thank you for sending in the updates. What's the reasoning behind opting out to set `interactive=true` for v7?

**Comment by tolmasoft** [comment]
[Migration Guide](https://github.com/pixijs/pixijs/wiki/v7-Migration-Guide#-replaces-interactionmanager-with-eventsystem)

**Comment by Mwni** [comment]
I read that, but couldn't find anything about not setting the interactive property...

**Comment by tolmasoft** [comment]
Sorry) I'm find info in [Release 7.2.0 PIXI.JS](https://github.com/pixijs/pixijs/releases/tag/v7.2.0)

**Comment by tolmasoft** [comment]
In version 7.2.4 when i set interactive=true i have warning
![image](https://github.com/Mwni/pixi-text-input/assets/7280954/89dbca14-7c7f-4327-9be4-b7efa38be9f8)

**Comment by lmagitem** [comment]
You're wonderful @tolmasoft, thank you for sharing <3
