### ISSUE TITLE
Not work with PIXI v7 and not work in TypeScript

### ISSUE THREAD

**Issue by tolmasoft** [Mwni/pixi-text-input#43]
I'm modify original code and all working. This is not the best solution, but for now it suits me.

**before use!**

`window.PIXI = PIXI`; 

**And declare window.PIXI in index.d.ts!** 
`declare global {
    interface Window {
        PIXI: any
    }
}
`

[textinput.ts](https://tolmasoft.github.io/textinput.ts)

**Comment by Mwni** [comment]
This is indeed suboptimal. I will pay attention to it in the next update.
