### ISSUE TITLE
TextIndent

### ISSUE THREAD

**Issue by Aiysen** [Mwni/pixi-text-input#7]
Hello

When using css textIndent, text in input form start jump to beginning when unfocus form.
https://www.pixiplayground.com/#/edit/ikn~oQk~V1nCYrVIFm~XI

And placeholder did not consider this prop.

**Comment by Aiysen** [comment]
Same problem width letterSpacing

**Comment by Mwni** [comment]
171da7a9d2043e7fe86310acd7deecd59794bfaf
It only works for `px` units. There is no easy way to convert other units to pixels.
